import "./globals.css";
import 'mapbox-gl/dist/mapbox-gl.css';
// import { Gabarito } from "next/font/google";
import { Gabarito as FontSans } from "next/font/google";
import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/context/theme-provider";
import ReactQueryClientProvider from "@/context/ReactQueryClientProvider";
import ReactMapProvider from '@/context/ReactMapProvider'
import { Toaster } from "react-hot-toast";

// const gabarito = Gabarito({ subsets: ["latin"] });
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: process.env.NEXT_PUBLIC_APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <body className={gabarito.className}>{children}</body> */}
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ReactQueryClientProvider>
          <ReactMapProvider>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <Toaster />
                {children}
                {/* <Toaster richColors /> */}
              </ThemeProvider>
          </ReactMapProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
